#!/usr/bin/bash
#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License, Version 1.0 only
# (the "License").  You may not use this file except in compliance
# with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#
# Copyright 2013 Jacques Marneweck.  All rights reserved.
# Use is subject to license terms.
#
# Fetches SmartOS Platform Image and writes them to the usbkey
#

set -o errexit
set -o pipefail
export PS4='[\D{%FT%TZ}] ${BASH_SOURCE}:${LINENO}: ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'
set -o xtrace

IMAGE=$1
if [ -z $IMAGE ]; then
  echo "Usage: ${0} BUILD"
  echo "e.g. ${0} 20130419T073558Z"
  exit 1
fi

if [ ! -d /var/tmp/usbimg ]; then
  mkdir /var/tmp/usbimg  
fi

cd /var/tmp/usbimg

wget --no-check-cert https://download.joyent.com/pub/iso/smartos-${IMAGE}-USB.img.bz2
if [ $? -eq 1 ]; then
  echo "Unable to download the smartos ${IMAGE} build."
  exit 2
fi

bunzip2 smartos-${IMAGE}-USB.img.bz2
if [ $? -eq 1 ]; then
  echo "Cannot unzip usb image."
  exit 3
fi

drives=$(/usr/bin/rmformat | /usr/bin/grep "/dev/rdsk/" | /usr/bin/awk '{ print $4 }')
for drive in ${drives[@]}
do
  echo "Writing to ${drive}"
  dd if=/var/tmp/usbimg/smartos-${IMAGE}-USB.img  of=${drive} bs=1024k
done
